"""add_image_urls_to_chat_history

Revision ID: 168e71d0ba28
Revises: cdd8036b7b50
Create Date: 2026-02-07 05:21:49.206670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168e71d0ba28'
down_revision: Union[str, None] = 'cdd8036b7b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'image_urls')
    # ### end Alembic commands ###
