"""rename_session_id_to_id_add_user_session_id

Revision ID: 7ae875e525aa
Revises: add_logs_column
Create Date: 2026-02-01 09:12:24.503740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae875e525aa'
down_revision: Union[str, None] = 'add_logs_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_sessions', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('analysis_sessions', sa.Column('user_session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_analysis_sessions_user_session_id'), 'analysis_sessions', ['user_session_id'], unique=False)
    op.drop_column('analysis_sessions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_sessions', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_analysis_sessions_user_session_id'), table_name='analysis_sessions')
    op.drop_column('analysis_sessions', 'user_session_id')
    op.drop_column('analysis_sessions', 'id')
    # ### end Alembic commands ###
